// <auto-generated />
using System;
using Asp.netCoreDatPhongKS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Asp.netCoreDatPhongKS.Migrations
{
    [DbContext(typeof(HotelPlaceVipContext))]
    [Migration("20250424085503_ThiemDinh")]
    partial class ThiemDinh
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.ChiTietPhieuPhong", b =>
                {
                    b.Property<int>("ChiTietId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChiTietID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietId"), 1L, 1);

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PhieuDatPhongId")
                        .HasColumnType("int")
                        .HasColumnName("PhieuDatPhongID");

                    b.Property<int?>("PhongId")
                        .HasColumnType("int")
                        .HasColumnName("PhongID");

                    b.HasKey("ChiTietId")
                        .HasName("PK__ChiTietP__B117E9EAD34FC6E4");

                    b.HasIndex("PhieuDatPhongId");

                    b.HasIndex("PhongId");

                    b.ToTable("ChiTietPhieuPhong", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.DanhGium", b =>
                {
                    b.Property<int>("DanhGiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DanhGiaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DanhGiaId"), 1L, 1);

                    b.Property<int?>("Diem")
                        .HasColumnType("int");

                    b.Property<int?>("KhachHangId")
                        .HasColumnType("int")
                        .HasColumnName("KhachHangID");

                    b.Property<DateTime?>("NgayDanhGia")
                        .HasColumnType("datetime");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhongId")
                        .HasColumnType("int")
                        .HasColumnName("PhongID");

                    b.HasKey("DanhGiaId")
                        .HasName("PK__DanhGia__52C0CA2556B8202C");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("PhongId");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.HinhAnhPhong", b =>
                {
                    b.Property<int>("HinhAnhId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HinhAnhID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HinhAnhId"), 1L, 1);

                    b.Property<string>("DuongDan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PhongId")
                        .HasColumnType("int")
                        .HasColumnName("PhongID");

                    b.HasKey("HinhAnhId")
                        .HasName("PK__HinhAnhP__8EF32B7B597EE560");

                    b.HasIndex("PhongId");

                    b.ToTable("HinhAnhPhong", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.KhachHang", b =>
                {
                    b.Property<int>("KhachHangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KhachHangID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KhachHangId"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("KhachHangId");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.KhuyenMai", b =>
                {
                    b.Property<int>("KhuyenMaiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KhuyenMaiID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KhuyenMaiId"), 1L, 1);

                    b.Property<string>("MaKhuyenMai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<int?>("PhanTramGiam")
                        .HasColumnType("int");

                    b.HasKey("KhuyenMaiId");

                    b.ToTable("KhuyenMai", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.LoaiPhong", b =>
                {
                    b.Property<int>("LoaiPhongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LoaiPhongID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoaiPhongId"), 1L, 1);

                    b.Property<decimal?>("GiaCoBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LoaiPhongId");

                    b.ToTable("LoaiPhong", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.NhanVien", b =>
                {
                    b.Property<int>("NhanVienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NhanVienID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhanVienId"), 1L, 1);

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int")
                        .HasColumnName("TaiKhoanID");

                    b.HasKey("NhanVienId");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.PhanQuyen", b =>
                {
                    b.Property<int>("PhanQuyenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PhanQuyenID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhanQuyenId"), 1L, 1);

                    b.Property<bool?>("CoQuyen")
                        .HasColumnType("bit");

                    b.Property<string>("TenChucNang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("VaiTroId")
                        .HasColumnType("int")
                        .HasColumnName("VaiTroID");

                    b.HasKey("PhanQuyenId");

                    b.HasIndex("VaiTroId");

                    b.ToTable("PhanQuyen", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.PhieuDatPhong", b =>
                {
                    b.Property<int>("PhieuDatPhongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PhieuDatPhongID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhieuDatPhongId"), 1L, 1);

                    b.Property<int?>("KhachHangId")
                        .HasColumnType("int")
                        .HasColumnName("KhachHangID");

                    b.Property<int?>("KhuyenMaiId")
                        .HasColumnType("int")
                        .HasColumnName("KhuyenMaiID");

                    b.Property<string>("MaPhieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayDat")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayNhan")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayTra")
                        .HasColumnType("date");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PhieuDatPhongId");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("KhuyenMaiId");

                    b.ToTable("PhieuDatPhong", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.Phong", b =>
                {
                    b.Property<int>("PhongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PhongID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhongId"), 1L, 1);

                    b.Property<int?>("LoaiPhongId")
                        .HasColumnType("int")
                        .HasColumnName("LoaiPhongID");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoPhong")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TinhTrang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PhongId");

                    b.HasIndex("LoaiPhongId");

                    b.ToTable("Phong", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.TaiKhoan", b =>
                {
                    b.Property<int>("TaiKhoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TaiKhoanID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaiKhoanId"), 1L, 1);

                    b.Property<string>("MatKhau")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<int?>("VaiTroId")
                        .HasColumnType("int")
                        .HasColumnName("VaiTroID");

                    b.HasKey("TaiKhoanId");

                    b.HasIndex("VaiTroId");

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.ThanhToan", b =>
                {
                    b.Property<int>("ThanhToanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ThanhToanID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThanhToanId"), 1L, 1);

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime");

                    b.Property<int?>("PhieuDatPhongId")
                        .HasColumnType("int")
                        .HasColumnName("PhieuDatPhongID");

                    b.Property<string>("PhuongThuc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ThanhToanId");

                    b.HasIndex("PhieuDatPhongId");

                    b.ToTable("ThanhToan", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.VaiTro", b =>
                {
                    b.Property<int>("VaiTroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VaiTroID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VaiTroId"), 1L, 1);

                    b.Property<string>("TenVaiTro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VaiTroId");

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.ChiTietPhieuPhong", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.PhieuDatPhong", "PhieuDatPhong")
                        .WithMany("ChiTietPhieuPhongs")
                        .HasForeignKey("PhieuDatPhongId")
                        .HasConstraintName("FK__ChiTietPh__Phieu__4F7CD00D");

                    b.HasOne("Asp.netCoreDatPhongKS.Models.Phong", "Phong")
                        .WithMany("ChiTietPhieuPhongs")
                        .HasForeignKey("PhongId")
                        .HasConstraintName("FK__ChiTietPh__Phong__5070F446");

                    b.Navigation("PhieuDatPhong");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.DanhGium", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.KhachHang", "KhachHang")
                        .WithMany("DanhGia")
                        .HasForeignKey("KhachHangId")
                        .HasConstraintName("FK__DanhGia__KhachHa__412EB0B6");

                    b.HasOne("Asp.netCoreDatPhongKS.Models.Phong", "Phong")
                        .WithMany("DanhGia")
                        .HasForeignKey("PhongId")
                        .HasConstraintName("FK__DanhGia__PhongID__4222D4EF");

                    b.Navigation("KhachHang");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.HinhAnhPhong", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.Phong", "Phong")
                        .WithMany("HinhAnhPhongs")
                        .HasForeignKey("PhongId")
                        .HasConstraintName("FK__HinhAnhPh__Phong__3C69FB99");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.NhanVien", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("NhanViens")
                        .HasForeignKey("TaiKhoanId")
                        .HasConstraintName("FK__NhanVien__TaiKho__5EBF139D");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.PhanQuyen", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.VaiTro", "VaiTro")
                        .WithMany("PhanQuyens")
                        .HasForeignKey("VaiTroId")
                        .HasConstraintName("FK__PhanQuyen__VaiTr__5BE2A6F2");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.PhieuDatPhong", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.KhachHang", "KhachHang")
                        .WithMany("PhieuDatPhongs")
                        .HasForeignKey("KhachHangId")
                        .HasConstraintName("FK__PhieuDatP__Khach__4AB81AF0");

                    b.HasOne("Asp.netCoreDatPhongKS.Models.KhuyenMai", "KhuyenMai")
                        .WithMany("PhieuDatPhongs")
                        .HasForeignKey("KhuyenMaiId")
                        .HasConstraintName("FK__PhieuDatP__Khuye__4BAC3F29");

                    b.Navigation("KhachHang");

                    b.Navigation("KhuyenMai");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.Phong", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.LoaiPhong", "LoaiPhong")
                        .WithMany("Phongs")
                        .HasForeignKey("LoaiPhongId")
                        .HasConstraintName("FK__Phong__LoaiPhong__398D8EEE");

                    b.Navigation("LoaiPhong");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.TaiKhoan", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.VaiTro", "VaiTro")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("VaiTroId")
                        .HasConstraintName("FK__TaiKhoan__VaiTro__59063A47");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.ThanhToan", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.PhieuDatPhong", "PhieuDatPhong")
                        .WithMany("ThanhToans")
                        .HasForeignKey("PhieuDatPhongId")
                        .HasConstraintName("FK__ThanhToan__Phieu__5441852A");

                    b.Navigation("PhieuDatPhong");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.KhachHang", b =>
                {
                    b.Navigation("DanhGia");

                    b.Navigation("PhieuDatPhongs");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.KhuyenMai", b =>
                {
                    b.Navigation("PhieuDatPhongs");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.LoaiPhong", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.PhieuDatPhong", b =>
                {
                    b.Navigation("ChiTietPhieuPhongs");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.Phong", b =>
                {
                    b.Navigation("ChiTietPhieuPhongs");

                    b.Navigation("DanhGia");

                    b.Navigation("HinhAnhPhongs");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.TaiKhoan", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.VaiTro", b =>
                {
                    b.Navigation("PhanQuyens");

                    b.Navigation("TaiKhoans");
                });
#pragma warning restore 612, 618
        }
    }
}
