// <auto-generated />
using System;
using Asp.netCoreDatPhongKS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Asp.netCoreDatPhongKS.Migrations
{
    [DbContext(typeof(HotelPlaceVipContext))]
    [Migration("20250528162428_dn")]
    partial class dn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.ChiTietDichVu", b =>
                {
                    b.Property<int>("ChiTietDichVuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietDichVuId"), 1L, 1);

                    b.Property<int>("DichVuId")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PhieuDatPhongId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("ChiTietDichVuId");

                    b.HasIndex("DichVuId");

                    b.HasIndex("PhieuDatPhongId");

                    b.ToTable("ChiTietDichVu", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.ChiTietPhieuPhong", b =>
                {
                    b.Property<int>("ChiTietId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChiTietID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietId"), 1L, 1);

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PhieuDatPhongId")
                        .HasColumnType("int")
                        .HasColumnName("PhieuDatPhongID");

                    b.Property<int?>("PhongId")
                        .HasColumnType("int")
                        .HasColumnName("PhongID");

                    b.HasKey("ChiTietId")
                        .HasName("PK__ChiTietP__B117E9EAD34FC6E4");

                    b.HasIndex("PhieuDatPhongId");

                    b.HasIndex("PhongId");

                    b.ToTable("ChiTietPhieuPhong", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.DanhGium", b =>
                {
                    b.Property<int>("DanhGiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DanhGiaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DanhGiaId"), 1L, 1);

                    b.Property<int?>("Diem")
                        .HasColumnType("int");

                    b.Property<int?>("KhachHangId")
                        .HasColumnType("int")
                        .HasColumnName("KhachHangID");

                    b.Property<DateTime?>("NgayDanhGia")
                        .HasColumnType("datetime");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhongId")
                        .HasColumnType("int")
                        .HasColumnName("PhongID");

                    b.HasKey("DanhGiaId")
                        .HasName("PK__DanhGia__52C0CA2556B8202C");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("PhongId");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.DichVu", b =>
                {
                    b.Property<int>("DichVuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DichVuId"), 1L, 1);

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("DichVuId");

                    b.ToTable("DichVu", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.HoaDon", b =>
                {
                    b.Property<int>("HoaDonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoaDonId"), 1L, 1);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NgayLap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PhieuDatPhongId")
                        .HasColumnType("int");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTienDichVu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTienPhong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("HoaDonId");

                    b.HasIndex("PhieuDatPhongId");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.KhachHang", b =>
                {
                    b.Property<int>("KhachHangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KhachHangID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KhachHangId"), 1L, 1);

                    b.Property<string>("Cccd")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CCCD");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("KhachHangId");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.KhuyenMai", b =>
                {
                    b.Property<int>("KhuyenMaiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KhuyenMaiID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KhuyenMaiId"), 1L, 1);

                    b.Property<string>("MaKhuyenMai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("PhanTramGiam")
                        .HasColumnType("int");

                    b.Property<bool?>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("KhuyenMaiId");

                    b.ToTable("KhuyenMai", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.LoaiPhong", b =>
                {
                    b.Property<int>("LoaiPhongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LoaiPhongID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoaiPhongId"), 1L, 1);

                    b.Property<string>("AnhDemo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal?>("GiaCoBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("SoluongNguoi")
                        .HasColumnType("int");

                    b.Property<string>("TenLoai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LoaiPhongId");

                    b.ToTable("LoaiPhong", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.NhanVien", b =>
                {
                    b.Property<int>("NhanVienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NhanVienID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhanVienId"), 1L, 1);

                    b.Property<string>("Cccd")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CCCD");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int")
                        .HasColumnName("TaiKhoanID");

                    b.HasKey("NhanVienId");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.PhieuDatPhong", b =>
                {
                    b.Property<int>("PhieuDatPhongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PhieuDatPhongID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhieuDatPhongId"), 1L, 1);

                    b.Property<int?>("KhachHangId")
                        .HasColumnType("int")
                        .HasColumnName("KhachHangID");

                    b.Property<int?>("KhuyenMaiId")
                        .HasColumnType("int")
                        .HasColumnName("KhuyenMaiID");

                    b.Property<string>("MaPhieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayDat")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayNhan")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayTra")
                        .HasColumnType("date");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VnpTransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhieuDatPhongId");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("KhuyenMaiId");

                    b.ToTable("PhieuDatPhong", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.Phong", b =>
                {
                    b.Property<int>("PhongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PhongID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhongId"), 1L, 1);

                    b.Property<decimal?>("GiaPhong1Dem")
                        .HasColumnType("money");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HinhAnh2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HinhAnh3")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("LoaiPhongId")
                        .HasColumnType("int")
                        .HasColumnName("LoaiPhongID");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("SoLuongKhach")
                        .HasColumnType("int");

                    b.Property<string>("SoPhong")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TinhTrang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PhongId");

                    b.HasIndex("LoaiPhongId");

                    b.ToTable("Phong", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.Quyen", b =>
                {
                    b.Property<int>("QuyenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuyenId"), 1L, 1);

                    b.Property<string>("MaQuyen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("QuyenId");

                    b.HasIndex(new[] { "MaQuyen" }, "UQ__Quyen__1D4B7ED5D71DC5F4")
                        .IsUnique();

                    b.ToTable("Quyen", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.QuyenTaiKhoan", b =>
                {
                    b.Property<int>("TaiKhoanId")
                        .HasColumnType("int");

                    b.Property<int>("QuyenId")
                        .HasColumnType("int");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaiKhoanId", "QuyenId")
                        .HasName("PK__TaiKhoan__4B3B6DA39AADDB30");

                    b.HasIndex("QuyenId");

                    b.ToTable("QuyenTaiKhoan", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.TaiKhoan", b =>
                {
                    b.Property<int>("TaiKhoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TaiKhoanID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaiKhoanId"), 1L, 1);

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Hoten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<int?>("VaiTroId")
                        .HasColumnType("int")
                        .HasColumnName("VaiTroID");

                    b.HasKey("TaiKhoanId");

                    b.HasIndex("VaiTroId");

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.ThanhToan", b =>
                {
                    b.Property<int>("ThanhToanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ThanhToanID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThanhToanId"), 1L, 1);

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime");

                    b.Property<int?>("PhieuDatPhongId")
                        .HasColumnType("int")
                        .HasColumnName("PhieuDatPhongID");

                    b.Property<string>("PhuongThuc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ThanhToanId");

                    b.HasIndex("PhieuDatPhongId");

                    b.ToTable("ThanhToan", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.VaiTro", b =>
                {
                    b.Property<int>("VaiTroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VaiTroID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VaiTroId"), 1L, 1);

                    b.Property<string>("TenVaiTro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VaiTroId");

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.ChiTietDichVu", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.DichVu", "DichVu")
                        .WithMany("ChiTietDichVus")
                        .HasForeignKey("DichVuId")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDi__DichV__3493CFA7");

                    b.HasOne("Asp.netCoreDatPhongKS.Models.PhieuDatPhong", "PhieuDatPhong")
                        .WithMany("ChiTietDichVus")
                        .HasForeignKey("PhieuDatPhongId")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDi__Phieu__339FAB6E");

                    b.Navigation("DichVu");

                    b.Navigation("PhieuDatPhong");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.ChiTietPhieuPhong", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.PhieuDatPhong", "PhieuDatPhong")
                        .WithMany("ChiTietPhieuPhongs")
                        .HasForeignKey("PhieuDatPhongId")
                        .HasConstraintName("FK__ChiTietPh__Phieu__4F7CD00D");

                    b.HasOne("Asp.netCoreDatPhongKS.Models.Phong", "Phong")
                        .WithMany("ChiTietPhieuPhongs")
                        .HasForeignKey("PhongId")
                        .HasConstraintName("FK__ChiTietPh__Phong__5070F446");

                    b.Navigation("PhieuDatPhong");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.DanhGium", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.KhachHang", "KhachHang")
                        .WithMany("DanhGia")
                        .HasForeignKey("KhachHangId")
                        .HasConstraintName("FK__DanhGia__KhachHa__412EB0B6");

                    b.HasOne("Asp.netCoreDatPhongKS.Models.Phong", "Phong")
                        .WithMany("DanhGia")
                        .HasForeignKey("PhongId")
                        .HasConstraintName("FK__DanhGia__PhongID__4222D4EF");

                    b.Navigation("KhachHang");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.HoaDon", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.PhieuDatPhong", "PhieuDatPhong")
                        .WithMany("HoaDons")
                        .HasForeignKey("PhieuDatPhongId")
                        .IsRequired()
                        .HasConstraintName("FK__HoaDon__PhieuDat__3864608B");

                    b.Navigation("PhieuDatPhong");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.NhanVien", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("NhanViens")
                        .HasForeignKey("TaiKhoanId")
                        .HasConstraintName("FK__NhanVien__TaiKho__7A672E12");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.PhieuDatPhong", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.KhachHang", "KhachHang")
                        .WithMany("PhieuDatPhongs")
                        .HasForeignKey("KhachHangId")
                        .HasConstraintName("FK__PhieuDatP__Khach__4AB81AF0");

                    b.HasOne("Asp.netCoreDatPhongKS.Models.KhuyenMai", "KhuyenMai")
                        .WithMany("PhieuDatPhongs")
                        .HasForeignKey("KhuyenMaiId")
                        .HasConstraintName("FK__PhieuDatP__Khuye__4BAC3F29");

                    b.Navigation("KhachHang");

                    b.Navigation("KhuyenMai");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.Phong", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.LoaiPhong", "LoaiPhong")
                        .WithMany("Phongs")
                        .HasForeignKey("LoaiPhongId")
                        .HasConstraintName("FK__Phong__LoaiPhong__398D8EEE");

                    b.Navigation("LoaiPhong");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.QuyenTaiKhoan", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.Quyen", "Quyen")
                        .WithMany("QuyenTaiKhoans")
                        .HasForeignKey("QuyenId")
                        .IsRequired()
                        .HasConstraintName("FK__TaiKhoan___Quyen__19DFD96B");

                    b.HasOne("Asp.netCoreDatPhongKS.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("QuyenTaiKhoans")
                        .HasForeignKey("TaiKhoanId")
                        .IsRequired()
                        .HasConstraintName("FK__TaiKhoan___TaiKh__18EBB532");

                    b.Navigation("Quyen");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.TaiKhoan", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.VaiTro", "VaiTro")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("VaiTroId")
                        .HasConstraintName("FK__TaiKhoan__VaiTro__778AC167");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.ThanhToan", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.PhieuDatPhong", "PhieuDatPhong")
                        .WithMany("ThanhToans")
                        .HasForeignKey("PhieuDatPhongId")
                        .HasConstraintName("FK__ThanhToan__Phieu__5441852A");

                    b.Navigation("PhieuDatPhong");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.DichVu", b =>
                {
                    b.Navigation("ChiTietDichVus");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.KhachHang", b =>
                {
                    b.Navigation("DanhGia");

                    b.Navigation("PhieuDatPhongs");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.KhuyenMai", b =>
                {
                    b.Navigation("PhieuDatPhongs");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.LoaiPhong", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.PhieuDatPhong", b =>
                {
                    b.Navigation("ChiTietDichVus");

                    b.Navigation("ChiTietPhieuPhongs");

                    b.Navigation("HoaDons");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.Phong", b =>
                {
                    b.Navigation("ChiTietPhieuPhongs");

                    b.Navigation("DanhGia");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.Quyen", b =>
                {
                    b.Navigation("QuyenTaiKhoans");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.TaiKhoan", b =>
                {
                    b.Navigation("NhanViens");

                    b.Navigation("QuyenTaiKhoans");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.VaiTro", b =>
                {
                    b.Navigation("TaiKhoans");
                });
#pragma warning restore 612, 618
        }
    }
}
