// <auto-generated />
using System;
using Asp.netCoreDatPhongKS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Asp.netCoreDatPhongKS.Migrations
{
    [DbContext(typeof(HotelPlaceVipContext))]
    partial class HotelPlaceVipContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.ChiTietDonHangDichVu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DichVuId")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaDonHangDv")
                        .HasColumnType("int")
                        .HasColumnName("MaDonHangDV");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(29,2)")
                        .HasComputedColumnSql("([SoLuong]*[DonGia])", true);

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DichVuId" }, "IX_ChiTietDonHangDichVu_DichVuId");

                    b.HasIndex(new[] { "MaDonHangDv" }, "IX_ChiTietDonHangDichVu_MaDonHangDV");

                    b.ToTable("ChiTietDonHangDichVu", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.ChiTietPhieuPhong", b =>
                {
                    b.Property<int>("ChiTietId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChiTietID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietId"), 1L, 1);

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PhieuDatPhongId")
                        .HasColumnType("int")
                        .HasColumnName("PhieuDatPhongID");

                    b.Property<int?>("PhongId")
                        .HasColumnType("int")
                        .HasColumnName("PhongID");

                    b.HasKey("ChiTietId")
                        .HasName("PK__ChiTietP__B117E9EAD34FC6E4");

                    b.HasIndex(new[] { "PhieuDatPhongId" }, "IX_ChiTietPhieuPhong_PhieuDatPhongID");

                    b.HasIndex(new[] { "PhongId" }, "IX_ChiTietPhieuPhong_PhongID");

                    b.ToTable("ChiTietPhieuPhong", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.DanhGium", b =>
                {
                    b.Property<int>("DanhGiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DanhGiaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DanhGiaId"), 1L, 1);

                    b.Property<int?>("DichVuId")
                        .HasColumnType("int");

                    b.Property<int?>("Diem")
                        .HasColumnType("int");

                    b.Property<int?>("DonHangDichVuId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDanhGia")
                        .HasColumnType("datetime");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhieuDatPhongId")
                        .HasColumnType("int");

                    b.Property<int?>("PhongId")
                        .HasColumnType("int")
                        .HasColumnName("PhongID");

                    b.Property<int>("TaiKhoanId")
                        .HasColumnType("int");

                    b.HasKey("DanhGiaId")
                        .HasName("PK__DanhGia__52C0CA2556B8202C");

                    b.HasIndex(new[] { "DichVuId" }, "IX_DanhGia_DichVuId");

                    b.HasIndex(new[] { "DonHangDichVuId" }, "IX_DanhGia_DonHangDichVuId");

                    b.HasIndex(new[] { "PhieuDatPhongId" }, "IX_DanhGia_PhieuDatPhongId");

                    b.HasIndex(new[] { "PhongId" }, "IX_DanhGia_PhongID");

                    b.HasIndex(new[] { "TaiKhoanId" }, "IX_DanhGia_TaiKhoanId");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.DichVu", b =>
                {
                    b.Property<int>("DichVuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DichVuId"), 1L, 1);

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("DichVuId");

                    b.ToTable("DichVu", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.DonHangDichVu", b =>
                {
                    b.Property<int>("MaDonHangDv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonHangDv"), 1L, 1);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDat")
                        .HasColumnType("datetime");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDonHangDv")
                        .HasName("PK__DonHangD__A906C724482980CC");

                    b.HasIndex(new[] { "KhachHangId" }, "IX_DonHangDichVu_KhachHangId");

                    b.ToTable("DonHangDichVu", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"), 1L, 1);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhThucThanhToan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsKhachVangLai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("KhachHangId")
                        .HasColumnType("int")
                        .HasColumnName("KhachHangID");

                    b.Property<DateTime?>("NgayLap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NguoiLapDh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NguoiLapDH");

                    b.Property<decimal?>("SoTienConNo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TongTienDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal?>("TongTienPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValueSql("(N'Chưa thanh toán')");

                    b.HasKey("MaHoaDon")
                        .HasName("PK__HoaDon__835ED13BD5B92EFA");

                    b.HasIndex(new[] { "KhachHangId" }, "IX_HoaDon_KhachHangID");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.HoaDonDichVu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("HinhThucThanhToan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaDonHangDv")
                        .HasColumnType("int");

                    b.Property<int?>("MaHoaDonTong")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValueSql("('Chua thanh toán')");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "MaDonHangDv" }, "IX_HoaDonDichVu_MaDonHangDv");

                    b.HasIndex(new[] { "MaHoaDonTong" }, "IX_HoaDonDichVu_MaHoaDonTong");

                    b.ToTable("HoaDonDichVu", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.HoaDonPdp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("PhieuDatPhongId")
                        .HasColumnType("int")
                        .HasColumnName("PhieuDatPhongID");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "MaHoaDon" }, "IX_HoaDonPDP_MaHoaDon");

                    b.HasIndex(new[] { "PhieuDatPhongId" }, "UQ__HoaDonPD__53A722215C43A14A")
                        .IsUnique();

                    b.ToTable("HoaDonPDP", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.KhachHang", b =>
                {
                    b.Property<int>("KhachHangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KhachHangID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KhachHangId"), 1L, 1);

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CCCD");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int");

                    b.HasKey("KhachHangId");

                    b.HasIndex(new[] { "TaiKhoanId" }, "IX_KhachHang_TaiKhoanId");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.KhuyenMai", b =>
                {
                    b.Property<int>("KhuyenMaiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KhuyenMaiID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KhuyenMaiId"), 1L, 1);

                    b.Property<string>("MaKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PhanTramGiam")
                        .HasColumnType("int");

                    b.Property<bool?>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("KhuyenMaiId");

                    b.ToTable("KhuyenMai", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.LienHeVoiCtoi", b =>
                {
                    b.Property<int>("LienHeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LienHeId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayGui")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LienHeId")
                        .HasName("PK__LienHeVo__53D769847D2D6696");

                    b.HasIndex(new[] { "KhachHangId" }, "IX_LienHeVoiCToi_KhachHangId");

                    b.HasIndex(new[] { "TaiKhoanId" }, "IX_LienHeVoiCToi_TaiKhoanId");

                    b.ToTable("LienHeVoiCToi", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.LoaiPhong", b =>
                {
                    b.Property<int>("LoaiPhongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LoaiPhongID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoaiPhongId"), 1L, 1);

                    b.Property<string>("AnhDemo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("GiaCoBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("SoluongNguoi")
                        .HasColumnType("int");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LoaiPhongId");

                    b.ToTable("LoaiPhong", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.NhanVien", b =>
                {
                    b.Property<int>("NhanVienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NhanVienID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhanVienId"), 1L, 1);

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CCCD");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int")
                        .HasColumnName("TaiKhoanID");

                    b.HasKey("NhanVienId");

                    b.HasIndex(new[] { "TaiKhoanId" }, "IX_NhanVien_TaiKhoanID");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.PhieuDatPhong", b =>
                {
                    b.Property<int>("PhieuDatPhongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PhieuDatPhongID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhieuDatPhongId"), 1L, 1);

                    b.Property<int?>("KhachHangId")
                        .HasColumnType("int")
                        .HasColumnName("KhachHangID");

                    b.Property<int?>("KhuyenMaiId")
                        .HasColumnType("int")
                        .HasColumnName("KhuyenMaiID");

                    b.Property<string>("MaPhieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoMoTransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayDat")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayNhan")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTra")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("SoTienCoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SoTienDaThanhToan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TinhTrangSuDung")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VnpTransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhieuDatPhongId");

                    b.HasIndex(new[] { "KhachHangId" }, "IX_PhieuDatPhong_KhachHangID");

                    b.HasIndex(new[] { "KhuyenMaiId" }, "IX_PhieuDatPhong_KhuyenMaiID");

                    b.ToTable("PhieuDatPhong", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.Phong", b =>
                {
                    b.Property<int>("PhongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PhongID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhongId"), 1L, 1);

                    b.Property<decimal?>("GiaPhong1Dem")
                        .IsRequired()
                        .HasColumnType("money");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HinhAnh2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HinhAnh3")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("LoaiPhongId")
                        .HasColumnType("int")
                        .HasColumnName("LoaiPhongID");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("SoLuongKhach")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("SoPhong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PhongId");

                    b.HasIndex(new[] { "LoaiPhongId" }, "IX_Phong_LoaiPhongID");

                    b.ToTable("Phong", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.Quyen", b =>
                {
                    b.Property<int>("QuyenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuyenId"), 1L, 1);

                    b.Property<string>("MaQuyen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("QuyenId");

                    b.HasIndex(new[] { "MaQuyen" }, "UQ__Quyen__1D4B7ED5D71DC5F4")
                        .IsUnique();

                    b.ToTable("Quyen", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.QuyenTaiKhoan", b =>
                {
                    b.Property<int>("TaiKhoanId")
                        .HasColumnType("int");

                    b.Property<int>("QuyenId")
                        .HasColumnType("int");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaiKhoanId", "QuyenId")
                        .HasName("PK__TaiKhoan__4B3B6DA39AADDB30");

                    b.HasIndex(new[] { "QuyenId" }, "IX_QuyenTaiKhoan_QuyenId");

                    b.ToTable("QuyenTaiKhoan", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.TaiKhoan", b =>
                {
                    b.Property<int>("TaiKhoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TaiKhoanID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaiKhoanId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Hoten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<int?>("VaiTroId")
                        .HasColumnType("int")
                        .HasColumnName("VaiTroID");

                    b.HasKey("TaiKhoanId");

                    b.HasIndex(new[] { "VaiTroId" }, "IX_TaiKhoan_VaiTroID");

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.VaiTro", b =>
                {
                    b.Property<int>("VaiTroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VaiTroID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VaiTroId"), 1L, 1);

                    b.Property<string>("TenVaiTro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VaiTroId");

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.ChiTietDonHangDichVu", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.DichVu", "DichVu")
                        .WithMany("ChiTietDonHangDichVus")
                        .HasForeignKey("DichVuId")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDo__DichV__3EDC53F0");

                    b.HasOne("Asp.netCoreDatPhongKS.Models.DonHangDichVu", "MaDonHangDvNavigation")
                        .WithMany("ChiTietDonHangDichVus")
                        .HasForeignKey("MaDonHangDv")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDo__MDHDV__3DE82FB7");

                    b.Navigation("DichVu");

                    b.Navigation("MaDonHangDvNavigation");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.ChiTietPhieuPhong", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.PhieuDatPhong", "PhieuDatPhong")
                        .WithMany("ChiTietPhieuPhongs")
                        .HasForeignKey("PhieuDatPhongId")
                        .HasConstraintName("FK__ChiTietPh__Phieu__4F7CD00D");

                    b.HasOne("Asp.netCoreDatPhongKS.Models.Phong", "Phong")
                        .WithMany("ChiTietPhieuPhongs")
                        .HasForeignKey("PhongId")
                        .HasConstraintName("FK__ChiTietPh__Phong__5070F446");

                    b.Navigation("PhieuDatPhong");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.DanhGium", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.DichVu", "DichVu")
                        .WithMany("DanhGia")
                        .HasForeignKey("DichVuId")
                        .HasConstraintName("FK_DanhGium_DichVu");

                    b.HasOne("Asp.netCoreDatPhongKS.Models.DonHangDichVu", "DonHangDichVu")
                        .WithMany("DanhGia")
                        .HasForeignKey("DonHangDichVuId");

                    b.HasOne("Asp.netCoreDatPhongKS.Models.PhieuDatPhong", "PhieuDatPhong")
                        .WithMany("DanhGia")
                        .HasForeignKey("PhieuDatPhongId");

                    b.HasOne("Asp.netCoreDatPhongKS.Models.Phong", "Phong")
                        .WithMany("DanhGia")
                        .HasForeignKey("PhongId")
                        .HasConstraintName("FK__DanhGia__PhongID__4222D4EF");

                    b.HasOne("Asp.netCoreDatPhongKS.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("DanhGia")
                        .HasForeignKey("TaiKhoanId")
                        .IsRequired()
                        .HasConstraintName("FK_DanhGium_TaiKhoan");

                    b.Navigation("DichVu");

                    b.Navigation("DonHangDichVu");

                    b.Navigation("PhieuDatPhong");

                    b.Navigation("Phong");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.DonHangDichVu", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.KhachHang", "KhachHang")
                        .WithMany("DonHangDichVus")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_DonHangDichVu_KhachHang");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.HoaDon", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("KhachHangId")
                        .HasConstraintName("FK__HoaDon__KhachHan__2610A626");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.HoaDonDichVu", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.DonHangDichVu", "MaDonHangDvNavigation")
                        .WithMany("HoaDonDichVus")
                        .HasForeignKey("MaDonHangDv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HoaDonDichVu_DonHangDichVu");

                    b.HasOne("Asp.netCoreDatPhongKS.Models.HoaDon", "MaHoaDonTongNavigation")
                        .WithMany("HoaDonDichVus")
                        .HasForeignKey("MaHoaDonTong")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_HoaDonDichVu_HoaDon");

                    b.Navigation("MaDonHangDvNavigation");

                    b.Navigation("MaHoaDonTongNavigation");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.HoaDonPdp", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.HoaDon", "MaHoaDonNavigation")
                        .WithMany("HoaDonPdps")
                        .HasForeignKey("MaHoaDon")
                        .HasConstraintName("FK__HoaDonPDP__MaHoa__55BFB948");

                    b.HasOne("Asp.netCoreDatPhongKS.Models.PhieuDatPhong", "PhieuDatPhong")
                        .WithOne("HoaDonPdp")
                        .HasForeignKey("Asp.netCoreDatPhongKS.Models.HoaDonPdp", "PhieuDatPhongId")
                        .IsRequired()
                        .HasConstraintName("FK__HoaDonPDP__Phieu__56B3DD81");

                    b.Navigation("MaHoaDonNavigation");

                    b.Navigation("PhieuDatPhong");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.KhachHang", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("KhachHangs")
                        .HasForeignKey("TaiKhoanId")
                        .HasConstraintName("FK_KhachHang_TaiKhoan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.LienHeVoiCtoi", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.KhachHang", "KhachHang")
                        .WithMany("LienHeVoiCtois")
                        .HasForeignKey("KhachHangId")
                        .HasConstraintName("FK__LienHeVoi__Khach__5CA1C101");

                    b.HasOne("Asp.netCoreDatPhongKS.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("LienHeVoiCtois")
                        .HasForeignKey("TaiKhoanId")
                        .HasConstraintName("FK__LienHeVoi__TaiKh__5D95E53A");

                    b.Navigation("KhachHang");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.NhanVien", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("NhanViens")
                        .HasForeignKey("TaiKhoanId")
                        .HasConstraintName("FK__NhanVien__TaiKho__7A672E12");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.PhieuDatPhong", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.KhachHang", "KhachHang")
                        .WithMany("PhieuDatPhongs")
                        .HasForeignKey("KhachHangId")
                        .HasConstraintName("FK__PhieuDatP__Khach__4AB81AF0");

                    b.HasOne("Asp.netCoreDatPhongKS.Models.KhuyenMai", "KhuyenMai")
                        .WithMany("PhieuDatPhongs")
                        .HasForeignKey("KhuyenMaiId")
                        .HasConstraintName("FK__PhieuDatP__Khuye__4BAC3F29");

                    b.Navigation("KhachHang");

                    b.Navigation("KhuyenMai");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.Phong", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.LoaiPhong", "LoaiPhong")
                        .WithMany("Phongs")
                        .HasForeignKey("LoaiPhongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Phong__LoaiPhong__398D8EEE");

                    b.Navigation("LoaiPhong");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.QuyenTaiKhoan", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.Quyen", "Quyen")
                        .WithMany("QuyenTaiKhoans")
                        .HasForeignKey("QuyenId")
                        .IsRequired()
                        .HasConstraintName("FK__TaiKhoan___Quyen__19DFD96B");

                    b.HasOne("Asp.netCoreDatPhongKS.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("QuyenTaiKhoans")
                        .HasForeignKey("TaiKhoanId")
                        .IsRequired()
                        .HasConstraintName("FK__TaiKhoan___TaiKh__18EBB532");

                    b.Navigation("Quyen");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.TaiKhoan", b =>
                {
                    b.HasOne("Asp.netCoreDatPhongKS.Models.VaiTro", "VaiTro")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("VaiTroId")
                        .HasConstraintName("FK__TaiKhoan__VaiTro__778AC167");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.DichVu", b =>
                {
                    b.Navigation("ChiTietDonHangDichVus");

                    b.Navigation("DanhGia");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.DonHangDichVu", b =>
                {
                    b.Navigation("ChiTietDonHangDichVus");

                    b.Navigation("DanhGia");

                    b.Navigation("HoaDonDichVus");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.HoaDon", b =>
                {
                    b.Navigation("HoaDonDichVus");

                    b.Navigation("HoaDonPdps");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.KhachHang", b =>
                {
                    b.Navigation("DonHangDichVus");

                    b.Navigation("HoaDons");

                    b.Navigation("LienHeVoiCtois");

                    b.Navigation("PhieuDatPhongs");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.KhuyenMai", b =>
                {
                    b.Navigation("PhieuDatPhongs");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.LoaiPhong", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.PhieuDatPhong", b =>
                {
                    b.Navigation("ChiTietPhieuPhongs");

                    b.Navigation("DanhGia");

                    b.Navigation("HoaDonPdp");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.Phong", b =>
                {
                    b.Navigation("ChiTietPhieuPhongs");

                    b.Navigation("DanhGia");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.Quyen", b =>
                {
                    b.Navigation("QuyenTaiKhoans");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.TaiKhoan", b =>
                {
                    b.Navigation("DanhGia");

                    b.Navigation("KhachHangs");

                    b.Navigation("LienHeVoiCtois");

                    b.Navigation("NhanViens");

                    b.Navigation("QuyenTaiKhoans");
                });

            modelBuilder.Entity("Asp.netCoreDatPhongKS.Models.VaiTro", b =>
                {
                    b.Navigation("TaiKhoans");
                });
#pragma warning restore 612, 618
        }
    }
}
